champions/urls.py
from django.urls import path
from . import views

app_name = "champions"

urlpatterns = [
    path("", views.ChampionView.as_view(), name="champion"),
    path("search/", views.search_view, name="search"),
    path("<int:pk>/", views.ChampionDetailView.as_view(), name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("champion/", include("champions.urls", namespace="champions")),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("tips/", include("tips.urls", namespace="tips")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
    path("signup/", views.UserSignupView.as_view(), name="signup"),
    path("logout/", views.log_out, name="logout"),
    path("<int:pk>/profile/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<div class="h-24 fixed bottom-0 mt-10 w-full border-t border-gray-700 bg-black flex justify-center items-center inset-x-0">
    <span class="text-white"> &copy; D o L  </span>
</div>

templates/partials/header.html
<div class="w-full bg-black-600 flex justify-between mt-5 items-center border-b border-gray-700 pb-2 pl-10">
    <a href="{% url 'core:home' %}"> 
        <img class="w-24" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRChn042-f9bIm1Tv6QmkKF60DiBAaLZdemhQ&usqp=CAU" alt="">
    </a>
    <div class=" font-semibold text-xl right-0" style="color:#C49937">
        <a href="{% url 'champions:champion' %}" class="mx-16">Champion</a>
        <a href="{% url 'products:home' %}" class="mr-16">Shop</a>
    {% if user.is_authenticated %}
         <a href="{% url 'users:logout' %}" class="ml-16">Log out</a>
        <a href="{% url 'users:profile' user.pk %}" class="mx-16">Profile</a>
    {% else %}
        <a href="{% url 'users:login' %}" class="ml-16">Log in</a>
        <a href="{% url 'users:signup' %}" class="mx-16">Sign up</a>
    {% endif %}
    </div>
</div>