config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("champion/", include("champions.urls", namespace="champions")),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("tips/", include("tips.urls", namespace="tips")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
]

products/urls.py
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path("", views.ProductView.as_view(), name="home"),
    path("search/", views.search_view, name="search"),
    path("<int:pk>/", views.ProductDetail.as_view(), name="detail"),
]

products/models.py
from django.db import models
from core import models as core_model


class AbstractModel(core_model.CoreModel):

    name = name = models.CharField(max_length=50)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Meterial(AbstractModel):

    pass


class Category(AbstractModel):

    name = models.CharField(max_length=50, default="의류")

    class Meta:
        verbose_name_plural = "Categories"


class Origin(AbstractModel):

    name = models.CharField(max_length=50, default="Korea")


class Product(core_model.CoreModel):

    """ Product Model Definition """

    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="product_image", null=True, blank=True)
    price = models.IntegerField()
    description = models.TextField()
    material = models.ManyToManyField("Meterial", related_name="products", blank=True)
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        related_name="products",
        blank=True,
        null=True,
    )
    origin = models.ForeignKey(
        "Origin",
        on_delete=models.CASCADE,
        related_name="products",
        blank=True,
        null=True,
    )
    soldout = models.BooleanField(default=False)

    def __str__(self):
        return self.name

products/views.py
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render
from users import mixins
from products import models


class ProductView(ListView):
    model = models.Product
    template_name = "products/home.html"
    context_object_name = "products"
    paginate_by = 30


class ProductDetail(mixins.LoginOnlyView, DetailView):
    model = models.Product
    template_name = "products/detail.html"
    context_object_name = "product"


def search_view(request):
    product = models.Product.objects.all()
    word = request.GET.get("word")
    product_search = product.filter(name__icontains=word)
    return render(
        request,
        "products/search.html",
        {
            "product_search": product_search,
        },
    )

templates/products/detail.html
{% extends 'base.html' %}
{% block title %}
{{product.name}}
{% endblock title %}

{% block content %}
<div class="text-white">
<img src="{{product.image}}"/>
{{product.name}}
{{product.price}}원
{{product.description}}
<div>
{% if product.soldout %}
sold out
{% else %}
수량 남음
{% endif %}
</div>
</div>
{% endblock content %} 

templates/products/home.html
{% extends 'base.html' %}
{% block title %}
Product
{% endblock title %}
{% block content %}
<div class="mb-24 text-white">
    <div class="mt-15 w-full h-24 flex justify-center items-center">
        <form class="flex" method="GET" action="{% url 'products:search' %}">
            <input class="mr-5 w-64 px-4 text-black rounded-md active:border-none outline-none text-lg" type="text" name="word">
            <button class="border border-white p-2 rounded-lg" type="submit" class="text-white"><i class="text-white fas fa-search"></i></button>
        </form>
    </div>
    <div class="grid grid-cols-3 gap-10 m-5">
            {% for p in products %}
            <a href="{% url 'products:detail' p.pk %}">
            <div class="border border-white rounded-md flex flex-col">
                <div class="w-full h-64 mr-5 bg-cover bg-center" style="background-image:url('{{p.image}}')"></div>
                <div class="flex flex-col items-center">
                    <p class="text-sm">{{p.name}}</p>
                    <p class="font-semibold">{{p.price}}원</p>
                </div>
            </div>
            </a>
            {% endfor %}
    </div>
    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}" class="text-red-500">
                <i class="fas fa-arrow-left fa-lg"></i>
            </a>
        {% endif %}
        <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
        
        {% if page_obj.has_next  %}
            <a href="?page={{page_obj.next_page_number}}" class="text-red-500">
                <i class="fas fa-arrow-right fa-lg"></i>
            </a>
        {% endif %}
    </div>
</div>
    

{% endblock content %}

templates/products/search.html
{% extends 'base.html' %}
{% block title %}
Search
{% endblock title %}
{% block content %}
    <div class="mt-15 w-full h-24 flex justify-center items-center">
        <form class="flex" method="GET" action="{% url 'products:search' %}">
            <input class="mr-5 w-64 px-4 text-black rounded-md active:border-none outline-none text-lg" type="text" name="word">
            <button class="border border-white p-2 rounded-lg" type="submit" class="text-white"><i class="text-white fas fa-search"></i></button>
        </form>
    </div>
    <div class="grid grid-cols-3 gap-10 mt-10 mx-16">
    {% for p in product_search %}
        <a href="{% url 'products:detail' p.pk %}">
            <div class="h-40 border border-gray-600 rounded-lg flex flex-col">
                <div class="flex justify-center items-center">
                    <span class="text-gray-300 font-semibold text-lg">{{p.name}}</span>
                </div>
                <div class="flex">
                    <div class="flex w-32 h-full items-center"></div>
                    <div class="text-white">{{p.price}}원</div>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>

{% endblock content %}