champions/urls.py
from django.urls import path
from . import views

app_name = "champions"

urlpatterns = [
    path("", views.ChampionView.as_view(), name="champion"),
    path("search/", views.search_view, name="search"),
    path("<int:pk>/", views.ChampionDetailView.as_view(), name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("champion/", include("champions.urls", namespace="champions")),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("tips/", include("tips.urls", namespace="tips")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
]

tips/urls.py
from django.urls import path
from . import views

app_name = "tips"

urlpatterns = [
    path("create/<int:pk>/", views.create_tips, name="tip"),
    path("delete/<int:pk>/", views.delete_tips, name="delete"),
]

champions/models.py
from django.db import models
from core import models as core_model


class AbsractModel(core_model.CoreModel):

    name = models.CharField(max_length=50)

    class Meta:
        abstract = True


class Position(AbsractModel):
    def __str__(self):
        return self.name


class Line(AbsractModel):
    def __str__(self):
        return self.name


class Champion(core_model.CoreModel):

    """ Champion Model Definition """

    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    square_image = models.ImageField(upload_to="champion_image", blank=True)
    loading_image = models.ImageField(upload_to="champion_image", blank=True)
    bio = models.TextField()
    position = models.ManyToManyField("Position", blank=True, related_name="champions")
    line = models.ManyToManyField("Line", blank=True, related_name="champions")

    def __str__(self):
        return self.name

tips/models.py
from django.db import models
from core import models as core_model


class Tip(core_model.CoreModel):

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="tips", null=True
    )
    champion = models.ForeignKey(
        "champions.Champion", on_delete=models.CASCADE, related_name="tips", null=True
    )
    recommand = models.IntegerField(null=True, default=0)
    description = models.TextField()

    def __str__(self):
        return f"{self.champion} Tip"

tips/forms.py
from django import forms
from . import models


class TipCreateForm(forms.ModelForm):
    class Meta:
        model = models.Tip
        fields = ("description",)

champions/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from champions.models import Champion


class ChampionView(ListView):
    model = Champion
    template_name = "champions/list.html"
    context_object_name = "champ"


class ChampionDetailView(DetailView):

    model = Champion
    template_name = "champions/detail.html"


def search_view(request):
    champion = Champion.objects.all()
    word = request.GET.get("word")
    search_champ = champion.filter(name__icontains=word)

    return render(request, "champions/search.html", {"search_champ": search_champ})

tips/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Tip
from users import mixins
from champions import models as champion_model
from users import models as user_model


@login_required(login_url="users:login")
def create_tips(request, pk):
    if request.method == "GET":
        user = request.user

        champion = champion_model.Champion.objects.get(pk=pk)
        form = forms.TipCreateForm
        return render(
            request,
            template_name="champions/tips.html",
            context={
                "champion": champion,
                "form": form,
                "user": user,
            },
        )

    if request.method == "POST":
        form = forms.TipCreateForm
        if form.is_valid:
            champion = champion_model.Champion.objects.get(pk=pk)
            user_pk = request.user.pk
            user = user_model.User.objects.get(pk=user_pk)
            description = request.POST.get("description")
            Tip.objects.create(
                user=user,
                champion=champion,
                description=description,
            )

            return redirect(reverse("champions:detail", kwargs={"pk": pk}))


@login_required(login_url="users:login")
def delete_tips(request, pk):
    if request.method == "GET":
        return render(request, "mixins/auth/delete.html")

    if request.method == "POST":
        tip = Tip.objects.get(pk=pk)
        tip.delete()
        return redirect(
            reverse("champions:champion"),
        )

templates/champions/detail.html
{% extends 'base.html' %}
{% block title %}
{{champion.name}}
{% endblock title %}
{% block content %}
<div class="mt-16 mx-48 h-full">
    <div class="text-white flex border border-white">
        <div class="h-full w-full m-3">
            <img src="{{champion.loading_image}}">
        </div>
        <div>
            <div class="text-4xl font-bold">{{champion.name}}</div>
            <div class="my-4">
                {% for c in champion.position.all %}
                <span class="text-xl">{{c}}</span>
                {% endfor %}
            </div>
            <div class="text-xl">
            <span>{{champion.bio}}</span>
            </div>
        </div>
    </div>
    {% if champion.tips.all %}
        {% for tip in champion.tips.all %}
            <div class="border-white border h-48 flex flex-col mt-10">
                <div class="flex h-full">
                    <div class="w-24 text-2xl flex flex-col justify-center items-center border-r border-white h-full">
                        <button id="up">🔼</button>
                        <span id = "number" class="text-white">{{tip.recommand}}</span>
                        <button id = "down">🔽</button>
                    </div>
                    <div class="text-white flex flex-col justify-center items-center border-r border-white w-48">
                        <span class="w-10 h-10 text-2xl border rounded-full border-white text-center"><i class="fas fa-user"></i></span>
                        <span class="mt-3">{{tip.user.nickname}}</span>
                    </div>
                    <div class="flex flex-col items-center justify-center w-full h-full text-white">
                        <div>
                            <span>{{tip.description}}</span>
                        </div>
                    </div>
                    {% if tip.user == user %}
                        <div class= "text-white text-xl mr-3 mt-3 ">
                            <a href="{% url 'tips:delete' tip.pk %}"><i class="fas fa-times-circle"></i>{{check_user}}</a>
                        </div>
                    {% else %}
                        <span class= "text-white mr-3 mt-3 text-xl"><i class="fas fa-laugh-wink"></i></span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
    <div class="text-white w-full flex items-center justify-center border border-white h-32 mt-16">
        <span> 챔피언 팁을 작성해주세요!</span>
    </div>
    {% endif %}
    <div class="text-white border-white w-64 h-20 border-2 m-auto mt-10 flex justify-center items-center text-bold text-2xl rounded-lg " style= "background-color:#E43E3E">
        <a href="{% url 'tips:tip' champion.pk %}">팁 작성하기</a>
    </div>
</div>
    <div class="w-full h-64 flex justify-center mt-24">
        <span class="text-white">관련상품</span>
    </div>
    
<script>
const number = document.getElementById("number");
const up = document.getElementById("up");
const down = document.getElementById("down");

let count = 0;

count = number.innerText;

const updateText = ()=>{
    number.innerText = count;
}
up.addEventListener("click", upHandle = ()=>{
    count = parseInt(count)+1;
    updateText();
})
down.addEventListener("click", downHandle= () =>{
    count = parseInt(count) -1;
    updateText();
})

</script>
{% endblock content %} 

templates/champions/list.html
{% extends 'base.html' %}
{% block title %}
Champions
{% endblock title %}

{% block content %}
<div class="mt-15 w-full h-24 flex justify-center items-center">
    <form class="flex" method="GET" action="{% url 'champions:search' %}">
    <input class="mr-5 w-64 px-4 rounded-md active:border-none outline-none text-lg " type="text" name="word" >
    <button class="border border-white p-2 rounded-lg" type="submit" class="text-white"><i class="text-white fas fa-search"></i></button>
    </form>
</div>
    <div class="grid grid-cols-3 gap-10 mt-10 mb-32">
    {% for c in champ %}
        <div class="h-40 border border-gray-600 rounded-lg flex flex-col">
            <div class="flex justify-center items-center">
                <span class="text-gray-300 font-semibold text-lg">{{c.name}}</span>
            </div>
            <div class="flex">
                <div class="flex w-32 h-full items-center">
                <a href="{% url 'champions:detail' c.pk %}">
                    <img class="opacity-50 hover:opacity-100" src="{{c.square_image}}">
                </a>
                </div>
                <div class="text-white">{{c.title}}</div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock content %}

templates/champions/search.html
{% extends 'base.html' %}
{% block title %}
Search
{% endblock title %}
{% block content %}
    <div class="mt-15 w-full h-24 flex justify-center items-center">
        <form class="flex" method="GET" action="{% url 'champions:search' %}">
            <input class="mr-5 w-64 px-4 rounded-md active:border-none outline-none text-lg" type="text" name="word">
            <button class="border border-white p-2 rounded-lg" type="submit" class="text-white"><i class="text-white fas fa-search"></i></button>
        </form>
    </div>
    <div class="grid grid-cols-3 gap-10 mt-10 mx-16">
    {% for c in search_champ %}
        <div class="h-40 border border-gray-600 rounded-lg flex flex-col">
            <div class="flex justify-center items-center">
                <span class="text-gray-300 font-semibold text-lg">{{c.name}}</span>
            </div>
            <div class="flex">
                <div class="flex w-32 h-full items-center">
                <a href="{% url 'champions:detail' c.pk %}">
                    <img class="opacity-50 hover:opacity-100" src="{{c.square_image}}">
                </a>
                </div>
                <div class="text-white">{{c.title}}</div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock content %}

templates/champions/tips.html
{% extends 'base.html' %}
{% block title %}
{{champion.name}} Tip
{% endblock title %}
{% block content %}


<form method="POST" class="text-white flex flex-col justify-center w-full">
    {% csrf_token %}
    <div class="w-full flex flex-col justify-center items-center mt-10 mb-48">
        <div class="text-lg font-bold px-10 py-4 border-white border rounded-lg ">{{champion}}</div>
        <div class="font-bold text-md mt-10">닉네임  {{user.nickname}}</div>
        <div class="text-black flex flex-col items-center">{% include "mixins/auth/input_form.html" %}</div>
    </div>
    
</form>
        

{% endblock content %}