config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("champion/", include("champions.urls", namespace="champions")),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("tips/", include("tips.urls", namespace="tips")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
    path("signup/", views.UserSignupView.as_view(), name="signup"),
    path("logout/", views.log_out, name="logout"),
    path("<int:pk>/profile/", views.UserProfileView.as_view(), name="profile"),
]

users/models.py
import sys
import os
import hashlib
import hmac
import base64
import requests
import time
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
    )

    nickname = models.CharField(max_length=10)
    avatar = models.ImageField(blank=True, upload_to="user_image")
    bio = models.TextField(max_length=1000)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    address = models.CharField(max_length=120, blank=True)
    birthdate = models.DateField(blank=True, null=True)


def make_signature():
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    accessKey = ""
    secretKey = ""
    access_key = accessKey
    secret_key = secretKey
    secret_key = bytes(secret_key, "UTF-8")
    method = "GET"
    uri = "/photos/puppy.jpg?query1=&query2"
    message = method + " " + uri + "\n" + timestamp + "\n" + access_key
    message = bytes(message, "UTF-8")
    signingKey = base64.b64encode(
        hmac.new(secret_key, message, digestmod=hashlib.sha256).digest()
    )
    return signingKey


def sms():
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    signkey = make_signature()
    headers = {
        "Content-Type": "application/json; charset=utf-8",
        "x-ncp-apigw-timestamp": timestamp,
        "x-ncp-iam-access-key": "",
        "x-ncp-apigw-signature-v2": signkey,
    }
    print(signkey)

    body = {
        "type": "SMS",
        "contentType": "COMM",
        "countryCode": "82",
        "from": "01039949377",
        "content": "인증",
        "messages": [{"to": "01039949377"}],
    }
    serviceId = ""

    return requests.post(
        f"https://sens.apigw.ntruss.com/sms/v2/services/{serviceId}/messages",
        headers=headers,
        json=body,
    )

users/forms.py
from django import forms
from users import models


class UserLoginForm(forms.Form):

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Email"}), label="이메일"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
        max_length=20,
        label="비밀번호",
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 잘못됬습니다."))
        except models.User.DoesNotExist:
            self.errors.clear
            self.add_error("email", forms.ValidationError("유저가 존재하지않습니다."))


class UserSignupForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("last_name", "email", "password", "password1")

    last_name = forms.CharField(widget=forms.TextInput, label="이름")
    email = forms.CharField(widget=forms.EmailInput, label="이메일")
    password = forms.CharField(widget=forms.PasswordInput, label="비밀번호")
    password1 = forms.CharField(widget=forms.PasswordInput, label="비밀번호 확인")

    def clean_password(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("패스워드가 일치하지 않습니다.")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import requests
import os
import google.oauth2.credentials
import google_auth_oauthlib.flow
from django.views.generic import DetailView, FormView, View
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import reverse, redirect
from users import models, forms, mixins


class UserLoginView(FormView):

    form_class = forms.UserLoginForm
    template_name = "users/login.html"
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class UserProfileView(mixins.LoginOnlyView, DetailView):

    model = models.User
    template_name = "users/profile.html"
    context_object_name = "user_obj"


class UserSignupView(FormView):

    form_class = forms.UserSignupForm
    template_name = "users/signup.html"
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def kakao_login(request):
    client_id = os.environ.get("KAKAO_KEY")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


def kakao_callback(request):
    code = request.GET.get("code")
    client_id = os.environ.get("KAKAO_KEY")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    token_request = requests.get(
        f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
    )
    token_json = token_request.json()
    if token_json is None:
        raise Exception("Can't do it")
    access_token = token_json.get("access_token")
    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    profile_json = profile_request.json()
    kakao_account = profile_json.get("kakao_account")
    kakao_profile = kakao_account.get("profile")
    kakao_nickname = kakao_profile.get("nickname")
    kakao_email = kakao_account.get("email")
    kakao_id = profile_json.get("id")

    if models.User.objects.exists():
        user = models.User.objects.get(email=kakao_email)
    else:
        user = models.User.objects.create(
            username=kakao_email,
            email=kakao_email,
            nickname=kakao_nickname,
        )
        user.save()

    login(request, user)
    return redirect(reverse("core:home"))


"""
def google_login(request):
    key = os.environ.get("GOOGLE_KEY")
    client_id = os.environ.get("GOOGLE_ID")

    flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
        "/User/users/documents/projects/Ddalki_of_legend/google_secret.json",
        client_id,
        scopes=['https://www.googleapis.com/auth/drive.metadata.readonly'])

    flow.redirect_uri = 'http://127.0.0.1:8000/users/login/google/callback'
    authorization_url= flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true')

    return redirect(
        f"https://language.googleapis.com/v1/documents:analyzeEntities?key={client_id}"
"""

templates/users/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock title %}
{% block content %}

<div class="flex justify-center w-full mb-32">
    <div class="w-2/5 flex flex-col items-center rounded-lg mt-5" style="background-color:#F9F9F9">
        <div class="text-3xl font-semibold my-20">로그인</div>
            <a class="mb-16 hover:text-yellow-300 flex justify-center items-center rounded-md bg-yellow-500 text-xl font-semibold py-5 my-2 border px-16" href="{% url 'users:kakao_login' %}">
            <i class="fas fa-comment mr-2"></i>
            카카오로 시작하기
            </a>
        {% include "mixins/auth/input_form.html" %}
        <div class="flex flex-col items-center">
            <div class=" text-gray-600 font-semibold"><span>로그인이 안 되시나요?</span></div>
            <div class="mt-3 mb-5 text-gray-600 text-sm font-bold">
                <a class="hover:text-blue-300" href="{% url 'users:signup' %}">계정 생성하기</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% block title %}
{{user_obj.nickname}} Profile
{% endblock title %}
{% block content %}
<div class="w-1/2 mx-auto mt-32 border-white border mb-32">
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.first_name}}{{user_obj.last_name}}</div>
    </div>
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.email}}</div>
    </div>
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.nickname}}</div>
    </div>
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.bio}}</div>
    </div>
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.address}}</div>
    </div>
    <div class="my-5">
        <span class="text-white">user</span>
        <div style = "background-color:beige" class="h-16 border-white border rounded-lg mx-8 mt-2">{{user_obj.avatar}}</div>
    </div>
    <div class="flex justify-around">
        <button class="bg-red-600 text-white text-xl w-38 px-8 rounded-lg py-5 my-10">프로필 수정</button>
        <button class="bg-red-600 text-white text-xl w-38 px-8 rounded-lg py-5 my-10">회원 탈퇴</button>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% block title %}
Sign up
{% endblock title %}
{% block content %}

<div class="flex justify-center w-full mb-32">
    <div class="w-2/5 flex flex-col items-center rounded-lg mt-5" style="background-color:#F9F9F9">
        <div class="text-3xl font-semibold my-24">회원가입</div>
        <a class="hover:text-yellow-300 flex justify-center items-center rounded-md bg-yellow-500 text-xl font-semibold py-5 my-2 border px-16" href="{% url 'users:kakao_login' %}">
            <i class="fas fa-comment mr-2"></i>
            카카오로 시작하기
            </a>
        {% include "mixins/auth/input_form.html" %}
        <div class="flex flex-col items-center">
        <div class=" text-gray-600 font-semibold">
            <span>계정이 이미 있으신가요?</span>
        </div>
        <div class="mt-3 mb-5 text-gray-600 text-sm font-bold">
            <a class="hover:text-blue-300" href="{% url 'users:login' %}">로그인 하기</a>  
        </div>
        </div>
    </div>
</div>
{% endblock content %}